Qt6 has changed function signature of QIconEngine::availableSizes()
It was 'const' in Qt5 but is no longer.
Identified by KDE FreeBSD/Qt5 CI:

kmix/gui/toggletoolbutton.cpp:62:71: error:
  non-virtual member function marked 'override' hides virtual member function
/usr/local/include/qt5/QtGui/qiconengine.h:77:26: note: hidden overloaded virtual
  function 'QIconEngine::availableSizes' declared here: different qualifiers
  ('const' vs unqualified)